### ISSUE TITLE
Do you know any way to contact julo42?

### ISSUE THREAD

**Issue by Francewhoa** [Bazon/WorkspaceSeparationOnDash#2]
What's wrong?
I try to view the page for the newest version of that extension at https://extensions.gnome.org/extension/876/isolated-workspaces/ 

But the site returns the following error message: 
=-=-=-=-=-
404 - Page not Found
We couldn't find the page you were looking for, /extension/876/isolated-workspaces/
=-=-=-=-=-

What have you tried?
I tried to contact julo42 at https://extensions.gnome.org/accounts/profile/julo42 But there is no form and no information to contact julo42 on that page. Do you know any way to contact julo42? If yes could you pass on this message to julo42?

I searched github for julo42 but no results

Automatically detected errors:

GNOME Shell Extensions did not detect any errors with this extension.

Version information:

    Shell version: 3.4.2
    Extension version: 6
    Debian version: 7.7 Wheezy at 64 bits; 
    Kernel Linux 3.2.0-4-amd64;

**Comment by N-Yuki** [comment]
I took over for julo42 a while back:
See https://extensions.gnome.org/extension/887/workspace-isolated-dash/ instead.

**Comment by Francewhoa** [comment]
Thanks :)

**Comment by Francewhoa** [comment]
I suggest to add a note in the description at https://extensions.gnome.org/extension/887/workspace-isolated-dash/

How about: This extension does not support old versions of Shell, so if you're on 3.4, it won't work.
